### ISSUE TITLE
Update pyshoco version installable via pip.

### ISSUE THREAD

**Issue by oliverjensen-wk** [Mego/shoco#5]
When using this via `pip install pyshoco` and under python3, compressing most strings results in a UnicodeDecodeError. Cloning this repo and installing pyshoco via `python setup.py install` solves the issue. Perhaps the Pypi version is out of date?

**Comment by Mego** [comment]
@oliverjensen-wk You're absolutely right. I pulled a bugfix PR and forgot to deploy to PyPI. I'm spoiled by Travis CI on other projects.
